[build-system]
requires = [
    "setuptools>=40.8.0",
    "wheel"
]

[project]
name = "random_data_generation"
version = "0.1.0"
description = "Random Data Generation"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
]
